import { useState, useEffect } from "react";
import { Button } from "./ui/button";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "./ui/select";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle } from "./ui/dialog";
import { Shield, Download, FileDown, Loader2, ArrowLeft, CheckCircle2, AlertCircle } from "lucide-react";

interface ReportPreviewProps {
  onBack: () => void;
}

export function ReportPreview({ onBack }: ReportPreviewProps) {
  const [exportFormat, setExportFormat] = useState("pdf");
  const [showExportModal, setShowExportModal] = useState(false);
  const [isExporting, setIsExporting] = useState(false);
  const [exportComplete, setExportComplete] = useState(false);
  const [report, setReport] = useState<any>(null);
  const [loading, setLoading] = useState(true);

  useEffect(() => {
    import("../services/api").then(({ generateReport }) => {
      generateReport().then((res) => {
        if (res.status === "success") {
          setReport(res.report);
        }
        setLoading(false);
      }).catch(() => setLoading(false));
    });
  }, []);

  const handleExport = () => {
    setShowExportModal(true);
    setIsExporting(true);
    setExportComplete(false);
    setTimeout(() => {
      setIsExporting(false);
      setExportComplete(true);
    }, 2000);
  };

  if (loading) {
    return (
      <div className="min-h-screen flex items-center justify-center" style={{ backgroundColor: "#FAF9F7" }}>
        <div className="text-center">
          <Loader2 className="w-8 h-8 animate-spin mx-auto mb-4" style={{ color: "#1B6CA8" }} />
          <p className="text-sm text-muted-foreground">Generating report...</p>
        </div>
      </div>
    );
  }

  const r = report || {};

  return (
    <div className="min-h-screen" style={{ backgroundColor: "#FAF9F7" }}>
      {/* Action Bar */}
      <div className="bg-white border-b px-8 py-4">
        <div className="max-w-5xl mx-auto flex items-center justify-between">
          <Button variant="outline" onClick={onBack} className="gap-2">
            <ArrowLeft className="w-4 h-4" />
            Back
          </Button>
          <div className="flex items-center gap-3">
            <Select value={exportFormat} onValueChange={setExportFormat}>
              <SelectTrigger className="w-[140px]">
                <SelectValue />
              </SelectTrigger>
              <SelectContent>
                <SelectItem value="pdf">PDF</SelectItem>
                <SelectItem value="docx">DOCX</SelectItem>
              </SelectContent>
            </Select>
            <Button onClick={handleExport} className="gap-2" style={{ backgroundColor: "#1B6CA8" }}>
              <Download className="w-4 h-4" />
              Download
            </Button>
          </div>
        </div>
      </div>

      {/* Report Container */}
      <div className="py-8 px-4">
        <div className="max-w-5xl mx-auto bg-white shadow-sm relative overflow-hidden">
          <div className="absolute inset-0 flex items-center justify-center opacity-[0.02] pointer-events-none">
            <Shield className="w-[600px] h-[600px]" />
          </div>

          <div className="relative z-10 px-16 py-12">

            {/* 1. Header */}
            <div className="border-b pb-8 mb-10" style={{ borderColor: "#E5E5E5" }}>
              <div className="flex items-start justify-between">
                <div className="space-y-6">
                  <div className="flex items-center gap-3">
                    <div className="w-12 h-12 rounded flex items-center justify-center" style={{ backgroundColor: "#1B6CA8" }}>
                      <Shield className="w-7 h-7 text-white" />
                    </div>
                    <span className="arabic-text text-3xl" style={{ color: "#1B6CA8" }}>&#1576;&#1615;&#1585;&#1607;&#1575;&#1606;</span>
                  </div>
                  <div className="space-y-2">
                    <h1 className="text-2xl" style={{ color: "#1B6CA8", fontWeight: 600 }}>
                      NCA-ECC Compliance Evaluation Report
                    </h1>
                    <p style={{ color: "#5A5A5A", fontSize: "14px" }}>
                      Generated by Burhan - AI-Powered Compliance Automation Platform
                    </p>
                  </div>
                </div>

                <div className="border rounded px-6 py-4 space-y-2 min-w-[300px]" style={{ borderColor: "#E5E5E5", backgroundColor: "#FAFAFA" }}>
                  <div className="flex justify-between text-sm">
                    <span style={{ color: "#5A5A5A" }}>Report Date:</span>
                    <span style={{ color: "#1B1B1B", fontWeight: 500 }}>{r.generated_at ? new Date(r.generated_at).toLocaleDateString('en-US', { year: 'numeric', month: 'long', day: 'numeric' }) : "—"}</span>
                  </div>
                  <div className="flex justify-between text-sm">
                    <span style={{ color: "#5A5A5A" }}>Total Controls:</span>
                    <span style={{ color: "#1B1B1B", fontWeight: 500 }}>{r.total_controls || 0}</span>
                  </div>
                  <div className="flex justify-between text-sm">
                    <span style={{ color: "#5A5A5A" }}>Evaluated:</span>
                    <span style={{ color: "#1B1B1B", fontWeight: 500 }}>{r.total_evaluated || 0}</span>
                  </div>
                  <div className="flex justify-between text-sm">
                    <span style={{ color: "#5A5A5A" }}>Validated:</span>
                    <span style={{ color: "#1B1B1B", fontWeight: 500 }}>{r.validated_count || 0}</span>
                  </div>
                </div>
              </div>
            </div>

            {/* 2. Executive Summary */}
            <section className="mb-10">
              <h2 className="text-xl mb-4" style={{ color: "#1B6CA8", fontWeight: 600 }}>1. Executive Summary</h2>
              <div className="space-y-4" style={{ color: "#5A5A5A", lineHeight: "1.8" }}>
                <p>
                  This report provides a summary of the organization's cybersecurity compliance status with the
                  National Cybersecurity Authority's Essential Cybersecurity Controls (NCA-ECC).
                </p>

                <div className="grid grid-cols-2 gap-6 pt-4">
                  {/* Overall Score */}
                  <div className="border rounded-lg p-6 text-center" style={{ borderColor: "#E5E5E5" }}>
                    <p className="text-sm mb-4" style={{ color: "#5A5A5A" }}>Overall Compliance</p>
                    <div className="flex items-center justify-center h-32 relative">
                      <svg width="120" height="120" viewBox="0 0 120 120">
                        <circle cx="60" cy="60" r="50" fill="none" stroke="#E5E5E5" strokeWidth="12"/>
                        <circle cx="60" cy="60" r="50" fill="none" stroke="#1B6CA8" strokeWidth="12"
                          strokeDasharray={`${(r.overall_score || 0) / 100 * 314} 314`}
                          transform="rotate(-90 60 60)"/>
                      </svg>
                      <div className="absolute text-center">
                        <div className="text-3xl" style={{ color: "#1B6CA8", fontWeight: 600 }}>{r.overall_score || 0}%</div>
                      </div>
                    </div>
                  </div>

                  {/* Summary Stats */}
                  <div className="border rounded-lg p-6" style={{ borderColor: "#E5E5E5" }}>
                    <p className="text-sm mb-4" style={{ color: "#5A5A5A" }}>Compliance Breakdown</p>
                    <div className="space-y-3">
                      {[
                        { label: "Compliant", value: r.total_compliant || 0, total: r.total_controls || 1, color: "#74C365" },
                        { label: "Partial", value: r.total_partial || 0, total: r.total_controls || 1, color: "#DBE64C" },
                        { label: "Non-Compliant", value: r.total_non_compliant || 0, total: r.total_controls || 1, color: "#ef4444" },
                        { label: "Not Evaluated", value: r.not_evaluated || 0, total: r.total_controls || 1, color: "#d1d5db" },
                      ].map((item, i) => (
                        <div key={i}>
                          <div className="flex justify-between text-xs mb-1" style={{ color: "#5A5A5A" }}>
                            <span>{item.label}</span>
                            <span>{item.value}</span>
                          </div>
                          <div className="h-2 rounded-full" style={{ backgroundColor: "#E5E5E5" }}>
                            <div className="h-2 rounded-full" style={{
                              backgroundColor: item.color,
                              width: `${Math.round((item.value / item.total) * 100)}%`
                            }}/>
                          </div>
                        </div>
                      ))}
                    </div>
                  </div>
                </div>
              </div>
            </section>

            {/* 3. Domain-Level Overview */}
            <section className="mb-10">
              <h2 className="text-xl mb-4" style={{ color: "#1B6CA8", fontWeight: 600 }}>2. Domain-Level Compliance Overview</h2>
              <div className="border rounded-lg overflow-hidden" style={{ borderColor: "#E5E5E5" }}>
                <table className="w-full">
                  <thead>
                    <tr style={{ backgroundColor: "#F9F9F9", borderBottom: "1px solid #E5E5E5" }}>
                      <th className="text-left px-4 py-3 text-sm" style={{ color: "#1B1B1B", fontWeight: 600 }}>Domain</th>
                      <th className="text-left px-4 py-3 text-sm" style={{ color: "#1B1B1B", fontWeight: 600 }}>Compliance</th>
                      <th className="text-left px-4 py-3 text-sm" style={{ color: "#1B1B1B", fontWeight: 600 }}>Evaluated</th>
                      <th className="text-left px-4 py-3 text-sm" style={{ color: "#1B1B1B", fontWeight: 600 }}>Status</th>
                    </tr>
                  </thead>
                  <tbody>
                    {(r.domain_results || []).length > 0 ? (r.domain_results || []).map((d: any, i: number) => (
                      <tr key={i} style={{ borderBottom: "1px solid #E5E5E5" }}>
                        <td className="px-4 py-3 text-sm" style={{ color: "#1B1B1B" }}>{d.name}</td>
                        <td className="px-4 py-3 text-sm" style={{ color: "#1B1B1B", fontWeight: 500 }}>{d.progress}%</td>
                        <td className="px-4 py-3 text-sm" style={{ color: "#5A5A5A" }}>{d.evaluated} / {d.total_controls}</td>
                        <td className="px-4 py-3 text-sm" style={{ color: "#5A5A5A" }}>{d.status}</td>
                      </tr>
                    )) : (
                      <tr><td colSpan={4} className="px-4 py-6 text-sm text-center" style={{ color: "#5A5A5A" }}>No data available</td></tr>
                    )}
                  </tbody>
                </table>
              </div>
            </section>

            {/* 4. Control-Level Findings */}
            <section className="mb-10">
              <h2 className="text-xl mb-4" style={{ color: "#1B6CA8", fontWeight: 600 }}>3. Control-Level Findings</h2>
              <div className="border rounded-lg overflow-hidden" style={{ borderColor: "#E5E5E5" }}>
                <table className="w-full">
                  <thead>
                    <tr style={{ backgroundColor: "#F9F9F9", borderBottom: "1px solid #E5E5E5" }}>
                      <th className="text-left px-4 py-3 text-sm" style={{ color: "#1B1B1B", fontWeight: 600 }}>Control ID</th>
                      <th className="text-left px-4 py-3 text-sm" style={{ color: "#1B1B1B", fontWeight: 600 }}>Name</th>
                      <th className="text-left px-4 py-3 text-sm" style={{ color: "#1B1B1B", fontWeight: 600 }}>Status</th>
                      <th className="text-left px-4 py-3 text-sm" style={{ color: "#1B1B1B", fontWeight: 600 }}>Evidence</th>
                      <th className="text-left px-4 py-3 text-sm" style={{ color: "#1B1B1B", fontWeight: 600 }}>Validated</th>
                    </tr>
                  </thead>
                  <tbody>
                    {(r.domain_results || []).flatMap((d: any) => d.control_findings || []).length > 0
                      ? (r.domain_results || []).flatMap((d: any) =>
                          (d.control_findings || []).map((f: any, i: number) => (
                            <tr key={`${f.control_id}-${i}`} style={{ borderBottom: "1px solid #E5E5E5" }}>
                              <td className="px-4 py-3 text-sm" style={{ color: "#1B6CA8", fontWeight: 500 }}>{f.control_id}</td>
                              <td className="px-4 py-3 text-sm" style={{ color: "#1B1B1B" }}>{f.name}</td>
                              <td className="px-4 py-3 text-sm">
                                <span className={`px-2 py-0.5 rounded text-xs ${
                                  f.status === "Compliant" ? "bg-green-100 text-green-700" :
                                  f.status === "Partial" ? "bg-amber-100 text-amber-700" :
                                  "bg-red-100 text-red-700"
                                }`}>{f.status}</span>
                              </td>
                              <td className="px-4 py-3 text-sm" style={{ color: "#5A5A5A" }}>{f.evidence_files?.join(", ") || "—"}</td>
                              <td className="px-4 py-3 text-sm">
                                {f.validated ? (
                                  <span className="flex items-center gap-1 text-green-600 text-xs">
                                    <CheckCircle2 className="w-3 h-3" /> {f.validator}
                                  </span>
                                ) : (
                                  <span className="text-xs text-gray-400">—</span>
                                )}
                              </td>
                            </tr>
                          ))
                        )
                      : (
                        <tr><td colSpan={5} className="px-4 py-6 text-sm text-center" style={{ color: "#5A5A5A" }}>No evaluations completed yet</td></tr>
                      )
                    }
                  </tbody>
                </table>
              </div>
            </section>

            {/* 5. Recommendations */}
            <section className="mb-10">
              <h2 className="text-xl mb-4" style={{ color: "#1B6CA8", fontWeight: 600 }}>4. Recommendations</h2>
              <div className="space-y-3">
                {(r.recommendations || []).length > 0
                  ? (r.recommendations || []).map((rec: string, i: number) => (
                      <div key={i} className="flex gap-3">
                        <span style={{ color: "#1B6CA8", fontWeight: 600 }}>{i + 1}.</span>
                        <p style={{ color: "#5A5A5A", lineHeight: "1.8" }}>{rec}</p>
                      </div>
                    ))
                  : <p style={{ color: "#5A5A5A" }}>No recommendations at this time.</p>
                }
              </div>
            </section>

            {/* 6. Conclusion */}
            <section className="mb-10">
              <h2 className="text-xl mb-4" style={{ color: "#1B6CA8", fontWeight: 600 }}>5. Conclusion</h2>
              <p style={{ color: "#5A5A5A", lineHeight: "1.8" }}>
                {r.total_evaluated > 0
                  ? `Out of ${r.total_controls} controls, ${r.total_evaluated} have been evaluated with an overall compliance score of ${r.overall_score}%. ${r.validated_count} controls have been validated by auditors. Regular assessments are recommended to maintain continuous compliance readiness.`
                  : "No evaluations have been completed yet. Start by uploading evidence for controls in the Evidence Compliance Management tab."
                }
              </p>
            </section>

            {/* 7. Verification */}
            <section className="mb-10">
              <h2 className="text-xl mb-6" style={{ color: "#1B6CA8", fontWeight: 600 }}>Verification and Approval</h2>
              <div className="border-2 rounded-lg p-8 text-center mb-8" style={{ borderColor: "#1B6CA8" }}>
                <div className="flex justify-center mb-4">
                  <div className="w-20 h-20 rounded-full border-4 flex items-center justify-center" style={{ borderColor: "#1B6CA8" }}>
                    <Shield className="w-10 h-10" style={{ color: "#1B6CA8" }} />
                  </div>
                </div>
                <p className="text-base mb-1" style={{ color: "#1B6CA8", fontWeight: 600 }}>
                  Official Verification Seal - Burhan AI Engine
                </p>
                <p className="text-sm" style={{ color: "#5A5A5A" }}>Digitally Generated Compliance Report</p>
              </div>
              <div className="grid grid-cols-2 gap-8">
                <div>
                  <p className="text-sm mb-2" style={{ color: "#5A5A5A" }}>Authorized Auditor Signature:</p>
                  <div className="border-b-2" style={{ borderColor: "#1B1B1B" }}><span style={{ color: "transparent" }}>_</span></div>
                </div>
                <div>
                  <p className="text-sm mb-2" style={{ color: "#5A5A5A" }}>Date:</p>
                  <div className="border-b-2" style={{ borderColor: "#1B1B1B" }}><span style={{ color: "transparent" }}>_</span></div>
                </div>
              </div>
            </section>

            {/* Footer */}
            <div className="border-t pt-6 text-center" style={{ borderColor: "#E5E5E5" }}>
              <p className="text-sm" style={{ color: "#5A5A5A" }}>
                Burhan - AI-Powered Compliance for NCA-ECC | Confidential Report for Internal Use Only
              </p>
            </div>
          </div>
        </div>
      </div>

      {/* Export Modal */}
      <Dialog open={showExportModal} onOpenChange={setShowExportModal}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>{isExporting ? "Exporting Report..." : "Export Complete"}</DialogTitle>
            <DialogDescription>
              {isExporting ? `Generating your ${exportFormat.toUpperCase()} report...` : `Report successfully exported as ${exportFormat.toUpperCase()}.`}
            </DialogDescription>
          </DialogHeader>
          <div className="flex flex-col items-center justify-center py-8">
            {isExporting ? (
              <Loader2 className="w-12 h-12 animate-spin" style={{ color: "#1B6CA8" }} />
            ) : (
              <div className="space-y-4 text-center">
                <div className="w-16 h-16 rounded-full flex items-center justify-center mx-auto" style={{ backgroundColor: "#E8F5E9" }}>
                  <FileDown className="w-8 h-8" style={{ color: "#2E7D32" }} />
                </div>
                <p className="text-sm" style={{ color: "#5A5A5A" }}>Your report has been downloaded to your device.</p>
                <Button onClick={() => setShowExportModal(false)} className="mt-4" style={{ backgroundColor: "#1B6CA8" }}>Close</Button>
              </div>
            )}
          </div>
        </DialogContent>
      </Dialog>
    </div>
  );
}
